const PHONE='5547933886303';
const materials=[
{id:'lock1',cat:'lock',icon:'🔐',title:'Fechadura eletrônica',sub:'Mais praticidade e segurança no dia a dia',text:'🔐 Mais praticidade e segurança para sua casa!\n\nInstalação de fechaduras eletrônicas com serviço profissional e organizado.\n📲 Solicite seu orçamento pelo WhatsApp: (47) 93388-6303\n\nMAICON AUTOMAÇÃO'},
{id:'lock2',cat:'lock',icon:'🚪',title:'Sem danificar a porta',sub:'Ideal também para imóveis alugados',text:'🏠 Mora de aluguel e quer usar fechadura eletrônica?\n\nEm muitos modelos é possível aproveitar a furação original da porta, evitando alterações desnecessárias. Faço a avaliação no local.\n📲 (47) 93388-6303 — Maicon Automação'},
{id:'lock3',cat:'lock',icon:'🛠️',title:'Manutenção de fechaduras',sub:'Configuração, ajustes e suporte',text:'🛠️ Sua fechadura eletrônica precisa de manutenção, configuração ou ajuste?\n\nEntre em contato e consulte o atendimento.\n📲 (47) 93388-6303 — Maicon Automação'},
{id:'electric1',cat:'electric',icon:'🚿',title:'Troca de chuveiro',sub:'Pequenos serviços residenciais',text:'🚿 Precisando trocar o chuveiro?\n\nFaço pequenos serviços elétricos residenciais, com atendimento combinado e organizado.\n📲 Chame no WhatsApp: (47) 93388-6303'},
{id:'electric2',cat:'electric',icon:'⚡',title:'Troca de resistência',sub:'Chuveiro parou de esquentar?',text:'⚡ Chuveiro parou de esquentar?\n\nFaço troca de resistência e pequenos reparos residenciais.\n📲 Consulte disponibilidade: (47) 93388-6303'},
{id:'electric3',cat:'electric',icon:'🔌',title:'Tomadas e interruptores',sub:'Troca de peças e pequenos reparos',text:'🔌 Precisa trocar tomada ou interruptor?\n\nAtendo pequenos serviços residenciais. Mande uma foto pelo WhatsApp para eu avaliar.\n📲 (47) 93388-6303'},
{id:'furn1',cat:'furniture',icon:'🪛',title:'Montagem de móveis',sub:'Montagem e desmontagem residencial',text:'🪛 Precisando montar um móvel?\n\nFaço montagem e desmontagem de móveis residenciais. Envie foto/modelo para orçamento.\n📲 WhatsApp: (47) 93388-6303'},
{id:'furn2',cat:'furniture',icon:'🧰',title:'Pequenos serviços',sub:'Uma ajuda para resolver o que está pendente',text:'🧰 Tem pequenos serviços pendentes em casa?\n\nTrabalho com montagem de móveis e alguns reparos residenciais simples. Envie uma foto e explique o que precisa.\n📲 (47) 93388-6303'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current=null, suggestion=Number(localStorage.suggestion||0)%materials.length;
function renderMaterials(filter='all'){const box=$('#materials');box.innerHTML='';materials.filter(x=>filter==='all'||x.cat===filter).forEach(m=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="preview ${m.cat}"><span class="icon">${m.icon}</span><div><strong>${m.title}</strong><br><small>${m.sub}</small></div></div><div class="cardBody"><button>Abrir material</button></div>`;el.querySelector('button').onclick=()=>openMaterial(m);box.append(el)})}
function today(){const m=materials[suggestion];$('#todayTitle').textContent=m.title;$('#todayText').textContent=m.sub;$('#todayOpen').onclick=()=>openMaterial(m)}
function openMaterial(m){current=m;$('#dTitle').textContent=m.title;$('#dText').value=m.text;drawArt(m);$('#materialDialog').showModal()}
function drawArt(m){const c=$('#artCanvas'),x=c.getContext('2d');const grad=x.createLinearGradient(0,0,1080,1080); if(m.cat==='lock'){grad.addColorStop(0,'#071722');grad.addColorStop(1,'#0b5360')}else if(m.cat==='electric'){grad.addColorStop(0,'#17150b');grad.addColorStop(1,'#5b4810')}else{grad.addColorStop(0,'#17110d');grad.addColorStop(1,'#4a3020')}x.fillStyle=grad;x.fillRect(0,0,1080,1080);x.fillStyle='#fff';x.font='700 62px system-ui';wrap(x,m.title.toUpperCase(),70,640,900,72);x.font='36px system-ui';x.fillStyle='#d7e5ea';wrap(x,m.sub,70,800,900,48);x.fillStyle='#14c8e4';x.fillRect(70,70,170,10);x.fillStyle='#fff';x.font='700 42px system-ui';x.fillText(m.cat==='lock'?'MAICON AUTOMAÇÃO':'SERVIÇOS RESIDENCIAIS',70,130);x.font='32px system-ui';x.fillStyle='#d9e4e8';x.fillText('WhatsApp (47) 93388-6303',70,990);x.font='150px system-ui';x.fillText(m.icon,800,230)}
function wrap(ctx,text,x,y,max,line){const words=text.split(' ');let l='';for(const w of words){const t=l+w+' ';if(ctx.measureText(t).width>max&&l){ctx.fillText(l,x,y);l=w+' ';y+=line}else l=t}ctx.fillText(l,x,y)}
function blobFromCanvas(){return new Promise(r=>$('#artCanvas').toBlob(r,'image/png',.95))}
$('#closeDialog').onclick=()=>$('#materialDialog').close();$('#copyText').onclick=async()=>{await navigator.clipboard.writeText($('#dText').value);$('#copyText').textContent='Copiado ✓';setTimeout(()=>$('#copyText').textContent='Copiar texto',1300)};
$('#saveArt').onclick=async()=>{const b=await blobFromCanvas(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`divulgacao-${current.id}.png`;a.click();URL.revokeObjectURL(a.href)};
$('#shareAll').onclick=async()=>{const b=await blobFromCanvas(),f=new File([b],`divulgacao-${current.id}.png`,{type:'image/png'});if(navigator.canShare?.({files:[f]})){await navigator.share({text:$('#dText').value,files:[f]})}else if(navigator.share){await navigator.share({text:$('#dText').value})}else{await navigator.clipboard.writeText($('#dText').value);alert('Texto copiado. Salve a arte e compartilhe pelo WhatsApp.')}};
$('#markShared').onclick=()=>{const h=JSON.parse(localStorage.history||'[]');h.unshift({title:current.title,date:new Date().toISOString()});localStorage.history=JSON.stringify(h.slice(0,50));renderHistory();$('#materialDialog').close()};
$('#nextSuggestion').onclick=()=>{suggestion=(suggestion+1)%materials.length;localStorage.suggestion=suggestion;today()};
$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMaterials(b.dataset.filter)});
function dayKey(){return new Date().toISOString().slice(0,10)}function renderGroups(){let groups=JSON.parse(localStorage.groups||'["Grupo do bairro","Condomínio / região","Classificados locais"]');let done=JSON.parse(localStorage.groupDone||'{}');const box=$('#groups');box.innerHTML='';groups.forEach((g,i)=>{const key=dayKey()+':'+i,el=document.createElement('div');el.className='group '+(done[key]?'done':'');el.innerHTML=`<label><input type="checkbox" ${done[key]?'checked':''}><span>${g}</span></label><button class="small ghost">✕</button>`;el.querySelector('input').onchange=e=>{done[key]=e.target.checked;localStorage.groupDone=JSON.stringify(done);renderGroups()};el.querySelector('button').onclick=()=>{groups.splice(i,1);localStorage.groups=JSON.stringify(groups);renderGroups()};box.append(el)})}
$('#addGroup').onclick=()=>{const n=prompt('Nome do grupo ou região:');if(!n)return;const g=JSON.parse(localStorage.groups||'[]');g.push(n);localStorage.groups=JSON.stringify(g);renderGroups()};
function renderHistory(){const h=JSON.parse(localStorage.history||'[]'),box=$('#history');box.innerHTML=h.length?'':'<div class="empty">Nenhuma divulgação registrada ainda.</div>';h.forEach(i=>{const d=new Date(i.date),el=document.createElement('div');el.className='historyItem';el.innerHTML=`<div><b>${i.title}</b><small>${d.toLocaleDateString('pt-BR')} • ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><span>✓</span>`;box.append(el)})}
$('#clearHistory').onclick=()=>{if(confirm('Limpar o histórico de divulgação?')){localStorage.removeItem('history');renderHistory()}};
$$('nav button').forEach((b,i)=>b.onclick=()=>{const ids=['top','materials','groups','history'];if(i===0)scrollTo({top:0,behavior:'smooth'});else document.querySelectorAll('section')[i].scrollIntoView({behavior:'smooth'})});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderMaterials();today();renderGroups();renderHistory();
