const PHONE='5547933886303';
const materials=[
{id:'lock1',cat:'lock',icon:'🔐',title:'Fechadura eletrônica',sub:'Mais praticidade e segurança no dia a dia',image:'assets/01-fechadura-eletronica.png',text:'🔐 Quer mais praticidade e segurança no dia a dia? Faço instalação e configuração de fechaduras eletrônicas, com orientação de uso e suporte pós-instalação.\n\n📲 Orçamento pelo WhatsApp: 47 93388-6303'},
{id:'lock2',cat:'lock',icon:'🚪',title:'Instalação preservando a estética da porta',sub:'Adaptação planejada e acabamento discreto',image:'assets/02-instalacao-preservando-porta.png',text:'🏠 Mora de aluguel ou quer instalar uma fechadura eletrônica sem comprometer a aparência da porta? Em muitos casos, fazemos a instalação aproveitando a furação original, com apenas as adaptações necessárias.\n\n🔧 Caso a fechadura antiga seja reinstalada futuramente, os furos adicionais ficam escondidos, preservando a estética original da porta.\n\n📲 Me envie uma foto da sua porta e da fechadura para avaliação: 47 93388-6303'},
{id:'lock3',cat:'lock',icon:'🛠️',title:'Manutenção e configuração de fechaduras',sub:'Configuração, ajustes e suporte',image:'assets/03-manutencao-configuracao-fechaduras.png',text:'🔧 Sua fechadura eletrônica está apresentando falhas ou precisa ser configurada? Faço configuração de usuários e senhas, troca de baterias, ajustes e manutenção em diversos modelos.\n\n📲 Chame no WhatsApp: 47 93388-6303'},
{id:'electric1',cat:'electric',icon:'🚿',title:'Troca de chuveiro e resistência',sub:'Pequenos serviços elétricos residenciais',image:'assets/04-troca-chuveiro-resistencia.png',text:'🚿 Chuveiro queimou ou parou de esquentar? Faço troca de chuveiro elétrico e resistência, com verificação da instalação.\n\n📲 Consulte disponibilidade: 47 93388-6303'},
{id:'electric2',cat:'electric',icon:'🔌',title:'Troca de tomadas e interruptores',sub:'Troca, instalação e pequenos reparos',image:'assets/05-troca-tomadas-interruptores.png',text:'⚡ Tomada quebrada, interruptor com problema ou precisando instalar um novo ponto? Faço pequenos serviços elétricos residenciais, com organização e bom acabamento.\n\n📲 Orçamento: 47 93388-6303'},
{id:'electric3',cat:'electric',icon:'💡',title:'Pequenos serviços elétricos residenciais',sub:'Soluções práticas para o dia a dia',image:'assets/06-pequenos-servicos-eletricos.png',text:'💡 Precisando resolver aqueles pequenos serviços elétricos de casa? Troca de luminárias, instalação de ventiladores, tomadas, interruptores e pequenos ajustes na rede elétrica.\n\n📲 Fale comigo: 47 93388-6303'},
{id:'furn1',cat:'furniture',icon:'🧰',title:'Desmontagem e remontagem de móveis',sub:'Para mudanças e reorganização de ambientes',image:'assets/07-desmontagem-remontagem-moveis.png',text:'🚚 Vai se mudar ou precisa reorganizar os móveis? Faço desmontagem e remontagem de móveis, incluindo reinstalação e regulagens no novo local.\n\n🔨 MAICON MONTAGENS\n📲 47 93388-6303'},
{id:'furn2',cat:'furniture',icon:'🛠️',title:'Instalação e ajustes em móveis',sub:'Regulagens, puxadores e alinhamentos',image:'assets/08-instalacao-ajustes-moveis.png',text:'🛠️ Porta desalinhada, gaveta pegando ou dobradiça precisando de regulagem? Faço ajustes, instalação de puxadores, alinhamento e pequenos serviços em móveis.\n\n🔨 MAICON MONTAGENS\n📲 47 93388-6303'},
{id:'furn3',cat:'furniture',icon:'🪛',title:'Montagem de móveis',sub:'Montagem, ajustes e regulagens',image:'assets/09-montagem-moveis.png',text:'🪑 Comprou móvel novo ou pela internet e precisa montar? Faço montagem, ajustes e regulagens, com cuidado e organização no ambiente.\n\n🔨 MAICON MONTAGENS\n📲 Orçamento: 47 93388-6303'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current=null, suggestion=Number(localStorage.suggestion||0)%materials.length;
function renderMaterials(filter='all'){const box=$('#materials');box.innerHTML='';materials.filter(x=>filter==='all'||x.cat===filter).forEach(m=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="preview ${m.cat}"><img src="${m.image}" alt="${m.title}" loading="lazy"><div class="previewLabel"><strong>${m.title}</strong><br><small>${m.sub}</small></div></div><div class="cardBody"><button>Abrir material</button></div>`;el.querySelector('button').onclick=()=>openMaterial(m);box.append(el)})}
function today(){const m=materials[suggestion];$('#todayTitle').textContent=m.title;$('#todayText').textContent=m.sub;$('#todayOpen').onclick=()=>openMaterial(m)}
function openMaterial(m){current=m;$('#dTitle').textContent=m.title;$('#dText').value=m.text;$('#artImage').src=m.image;$('#artImage').alt=m.title;$('#materialDialog').showModal()}
function drawArt(m){const c=$('#artCanvas'),x=c.getContext('2d');const grad=x.createLinearGradient(0,0,1080,1080); if(m.cat==='lock'){grad.addColorStop(0,'#071722');grad.addColorStop(1,'#0b5360')}else if(m.cat==='electric'){grad.addColorStop(0,'#17150b');grad.addColorStop(1,'#5b4810')}else{grad.addColorStop(0,'#17110d');grad.addColorStop(1,'#4a3020')}x.fillStyle=grad;x.fillRect(0,0,1080,1080);x.fillStyle='#fff';x.font='700 62px system-ui';wrap(x,m.title.toUpperCase(),70,640,900,72);x.font='36px system-ui';x.fillStyle='#d7e5ea';wrap(x,m.sub,70,800,900,48);x.fillStyle='#14c8e4';x.fillRect(70,70,170,10);x.fillStyle='#fff';x.font='700 42px system-ui';x.fillText(m.cat==='lock'?'MAICON AUTOMAÇÃO':'SERVIÇOS RESIDENCIAIS',70,130);x.font='32px system-ui';x.fillStyle='#d9e4e8';x.fillText('WhatsApp (47) 93388-6303',70,990);x.font='150px system-ui';x.fillText(m.icon,800,230)}
function wrap(ctx,text,x,y,max,line){const words=text.split(' ');let l='';for(const w of words){const t=l+w+' ';if(ctx.measureText(t).width>max&&l){ctx.fillText(l,x,y);l=w+' ';y+=line}else l=t}ctx.fillText(l,x,y)}
async function materialBlob(){const r=await fetch(current.image);return await r.blob()}
$('#closeDialog').onclick=()=>$('#materialDialog').close();$('#copyText').onclick=async()=>{await navigator.clipboard.writeText($('#dText').value);$('#copyText').textContent='Copiado ✓';setTimeout(()=>$('#copyText').textContent='Copiar texto',1300)};
$('#saveArt').onclick=async()=>{const b=await materialBlob(),a=document.createElement('a'),u=URL.createObjectURL(b);a.href=u;a.download=current.image.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('#shareAll').onclick=async()=>{const b=await materialBlob(),f=new File([b],current.image.split('/').pop(),{type:'image/png'});if(navigator.canShare?.({files:[f]})){await navigator.share({text:$('#dText').value,files:[f]})}else if(navigator.share){await navigator.share({text:$('#dText').value})}else{await navigator.clipboard.writeText($('#dText').value);alert('Texto copiado. Salve a arte e compartilhe pelo WhatsApp.')}};
$('#markShared').onclick=()=>{const h=JSON.parse(localStorage.history||'[]');h.unshift({title:current.title,date:new Date().toISOString()});localStorage.history=JSON.stringify(h.slice(0,50));renderHistory();$('#materialDialog').close()};
$('#nextSuggestion').onclick=()=>{suggestion=(suggestion+1)%materials.length;localStorage.suggestion=suggestion;today()};
$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMaterials(b.dataset.filter)});
function dayKey(){return new Date().toISOString().slice(0,10)}function renderGroups(){let groups=JSON.parse(localStorage.groups||'["Grupo do bairro","Condomínio / região","Classificados locais"]');let done=JSON.parse(localStorage.groupDone||'{}');const box=$('#groups');box.innerHTML='';groups.forEach((g,i)=>{const key=dayKey()+':'+i,el=document.createElement('div');el.className='group '+(done[key]?'done':'');el.innerHTML=`<label><input type="checkbox" ${done[key]?'checked':''}><span>${g}</span></label><button class="small ghost">✕</button>`;el.querySelector('input').onchange=e=>{done[key]=e.target.checked;localStorage.groupDone=JSON.stringify(done);renderGroups()};el.querySelector('button').onclick=()=>{groups.splice(i,1);localStorage.groups=JSON.stringify(groups);renderGroups()};box.append(el)})}
$('#addGroup').onclick=()=>{const n=prompt('Nome do grupo ou região:');if(!n)return;const g=JSON.parse(localStorage.groups||'[]');g.push(n);localStorage.groups=JSON.stringify(g);renderGroups()};
function renderHistory(){const h=JSON.parse(localStorage.history||'[]'),box=$('#history');box.innerHTML=h.length?'':'<div class="empty">Nenhuma divulgação registrada ainda.</div>';h.forEach(i=>{const d=new Date(i.date),el=document.createElement('div');el.className='historyItem';el.innerHTML=`<div><b>${i.title}</b><small>${d.toLocaleDateString('pt-BR')} • ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><span>✓</span>`;box.append(el)})}
$('#clearHistory').onclick=()=>{if(confirm('Limpar o histórico de divulgação?')){localStorage.removeItem('history');renderHistory()}};
$$('nav button').forEach((b,i)=>b.onclick=()=>{const ids=['top','materials','groups','history'];if(i===0)scrollTo({top:0,behavior:'smooth'});else document.querySelectorAll('section')[i].scrollIntoView({behavior:'smooth'})});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderMaterials();today();renderGroups();renderHistory();
